name: publish
on: [push]
jobs:
publish-reality-docker-image:
runs-on: alpine-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the reality-docker Docker image
run: |
       docker build . --tag ghcr.io/hangman1998/reality:latest
       docker run ghcr.io/hangman1998/reality:latest
       docker push ghcr.io/hangman1998/reality:latest